name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  # schedule:
  #  - cron:  '0,15,30,45 * * * *'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:  
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        number: [0,1]
        include:
          - driver-opts: ""
          - number: 0
            platforms: ""
            tag: single-platform
            provenance: false
          - number: 1
            platforms: ""
            tag: single-platform-provenance
            provenance: true
 
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
          driver-opts: |
            image=moby/buildkit:latest
            ${{ matrix.driver-opts }}

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          provenance: ${{ matrix.provenance }}
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.tag }}
